# .github/workflows/dispatch.yml in Repository A
name: Trigger Dispatch

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    uses: topshelfsoftware/.github/.github/workflows/repo-auto-tag.yaml@main
  
  auto-release:
    needs: auto-tag
    
    uses: topshelfsoftware/.github/.github/workflows/repo-create-release.yaml@main

  send_dispatch:
    needs: auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO_B_PAT }}" \
          https://api.github.com/repos/trpubins/demo-B/dispatches \
          -d '{"event_type":"triggered_by_repo_A"}'
